---
title: "Submissions to rOpenSci and CRAN"
author: "Maëlle Salmon"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
    toc: true
---

# Find submitted packages

```{r, cache = TRUE, warning = FALSE}
library("gh")
creation <- NULL
repo <- NULL
is_ok <- TRUE
page <- 1
while(is_ok){
  issues <- try(gh("/repos/:owner/:repo/issues", owner = "ropensci",
             repo = "onboarding", labels = "package",
             state = "all",
             page = page), silent = TRUE)
  is_ok <- is(issues, "list") & issues[[1]] != ""
  if(is_ok){
  page <- page + 1
  creation <- c(creation, vapply(issues, "[[", "", "created_at"))
  repo <- c(repo, vapply(issues, "[[", "", "body"))
  }
}

repo <- stringr::str_extract(repo, "Package:.*")
repo <- stringr::str_replace(repo, "Package: ", "")
```


```{r, warning = FALSE}
packages <- tibble::tibble(package = repo, 
                           ropensci_submission = lubridate::ymd_hms(creation))

packages <- unique(packages)
packages <- dplyr::filter(packages, !is.na(package))
packages
```

# Find the ones that are on CRAN

```{r}
library("crandb")
get_cran_oldest_date <- function(package){
  results <- try(package(package, version = "all"), silent = TRUE)
  if(is(results, "try-error")){
    date <- "9999-01-01 00 00 00"
  }else{
    date <- results$versions[[1]]$date
  }
  
  return(date)
}
get_cran_oldest_date("ropenaq")
```

```{r}
dates <- purrr::map_chr(packages$package, get_cran_oldest_date)
dates <- lubridate::ymd_hms(dates)
packages$cran_submission <- dates
packages <- dplyr::mutate(packages, 
                          ropensci_submission = lubridate::as_date(ropensci_submission), 
                          cran_submission = lubridate::as_date(cran_submission))
```


```{r}
knitr::kable(packages)
```

We're looking at `r nrow(packages)` packages. For `r sum(packages$cran_submission < packages$ropensci_submission)` there was a CRAN version before the rOpenSci submission. For `r sum(packages$cran_submission > packages$ropensci_submission)` there wasn't a CRAN version before the rOpenSci submission.